#!/usr/bin/env node
/**
 * Compile every corpus program with the real rustc and write EVIDENCE.md from
 * what the compiler actually said.
 *
 * Nothing about rustc's behaviour is hand-written anywhere in this repo. Error
 * codes, message text, and — the point of the whole exercise — the ORDER in
 * which rustc offers its suggestions, are all read out of `--error-format=json`.
 * CI reruns this and fails if the committed EVIDENCE.md drifts, so the claims
 * cannot rot away from the compiler.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

const EDITION = '2021'
const OUT = 'EVIDENCE.md'

function rustcVersion () {
  return execFileSync('rustc', ['--version'], { encoding: 'utf8' }).trim()
}

/** Compile one file and return every error diagnostic the compiler emitted. */
function diagnose (file) {
  const scratch = join(mkdtempSync(join(tmpdir(), 'clonetax-')), 'out')
  let raw = ''
  try {
    execFileSync('rustc', ['--edition', EDITION, '--error-format=json', file, '-o', scratch], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe']
    })
  } catch (err) {
    raw = err.stderr ?? ''
  }
  const errors = []
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue
    let d
    try {
      d = JSON.parse(line)
    } catch {
      continue
    }
    if (d.level !== 'error' || !d.code?.code) continue
    errors.push({
      code: d.code.code,
      message: d.message,
      // Order matters: this is the whole finding.
      suggestions: (d.children ?? [])
        .filter((c) => c.message && (c.level === 'help' || c.level === 'note'))
        .map((c) => ({ level: c.level, message: c.message.split('\n')[0] }))
    })
  }
  return errors
}

const manifest = JSON.parse(readFileSync('corpus/manifest.json', 'utf8'))
const version = rustcVersion()
const rows = []

for (const c of manifest.cases) {
  const errors = diagnose(join('corpus', c.file))
  if (errors.length === 0) {
    console.error(`FAIL ${c.file} compiled successfully — a corpus case must fail to compile.`)
    process.exit(1)
  }
  rows.push({ ...c, errors })
}

// What does rustc actually give an agent to act on? Answer from the data.
const silent = rows.filter((r) => r.errors.every((e) => e.suggestions.length === 0))
const cloneOnly = rows.filter((r) =>
  r.errors.some((e) => {
    const helps = e.suggestions.filter((s) => s.level === 'help')
    return helps.length > 0 && helps.every((s) => /clon/i.test(s.message))
  })
)

const md = []
md.push('# EVIDENCE — what the compiler actually says')
md.push('')
md.push('> Generated by `node scripts/extract.mjs`. Do not edit by hand.')
md.push(`> Compiler: \`${version}\` · edition ${EDITION} · ${rows.length} corpus programs`)
md.push('')
md.push('Every claim in this repository is produced by compiling the programs in `corpus/`')
md.push('and reading `rustc --error-format=json`. CI recompiles them and fails if this file')
md.push('drifts, so nothing here can quietly go stale.')
md.push('')
md.push('## Headline finding')
md.push('')
md.push(`On **${silent.length} of ${rows.length}** corpus cases rustc offers the agent **no actionable`)
md.push('suggestion at all** — no `help`, no `note`. It reports the conflict and stops.')
md.push('')
md.push(`On **${cloneOnly.length} of ${rows.length}**, the only \`help\` rustc gives is *"consider cloning the`)
md.push('value"*. `help` is the compiler\'s recommended action.')
md.push('')
md.push('So an agent that follows the compiler faithfully gets nothing to act on in most')
md.push('borrow conflicts, and gets told to clone in the one place it does get advice. Clone')
md.push('is the move that always compiles, so it becomes the default. That is the mechanism')
md.push('behind clone-spam — a guidance vacuum, not laziness.')
md.push('')
md.push('This section is recomputed from the compiler on every run. If a future rustc starts')
md.push('offering ownership fixes here, these numbers move and CI will flag the drift.')
md.push('')

for (const r of rows) {
  md.push(`## \`${r.file}\``)
  md.push('')
  md.push(`**Scenario.** ${r.scenario}`)
  md.push('')
  for (const e of r.errors) {
    md.push(`**Compiler says** — \`${e.code}\`: ${e.message}`)
    md.push('')
    if (e.suggestions.length) {
      md.push('| rank | level | suggestion |')
      md.push('|---|---|---|')
      e.suggestions.forEach((s, i) => md.push(`| ${i + 1} | \`${s.level}\` | ${s.message} |`))
    } else {
      md.push('_rustc offered no `help`/`note` suggestion for this one._')
    }
    md.push('')
  }
  md.push(`**What agents reach for.** ${r.tempting_fix}`)
  md.push('')
  md.push(`**Why that is wrong.** ${r.why_wrong}`)
  md.push('')
  md.push(`**Correct fix.** ${r.correct_fix}`)
  md.push('')
  md.push(`**Does clippy catch it?** ${r.clippy_catches ? 'Yes.' : 'No.'} ${r.clippy_note}`)
  md.push('')
}

writeFileSync(OUT, md.join('\n'))
console.log(`${OUT}: ${rows.length} cases · ${silent.length} with no suggestion at all · ${cloneOnly.length} where the only help is 'clone' (${version})`)
